str = input("Enter a string: ") 
words = str.split() 
words.reverse() 
new_str = " ".join(words) 
print("The string with reversed words is:", new_str) 
string = input("Enter a string: ") 
words = string.split() 
words.reverse() 
new_string = " ".join(words) 
print("The string with reversed words is:", new_string) 
